---
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_MECHE'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_NUCENG'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_CHEME'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_DMSE'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_CEE'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_EECS'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_AEROASTRO'

