---
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_MECHE Mechanical Engineering'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_NUCENG Nuclear Science and Engineering'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_CHEME Chemical Engineering'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_DMSE Dept Material Science and Engineering'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_CEE Civil & Environmental Engineering'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_EECS Electrical Engineering & Computer Science'
- account:
    authorization_id: '12345'
    category: 'ABET'
    effective_date: '2004-08-15'
    expiration_date: '2099-12-31'
    function: 'CAN EDIT ABET'
    is_active_now: 'Y'
    name: 'daries'
    account_has_access_to: 'D_AEROASTRO Aeronautics and Astronautics'

